//! Shell completion generation and user-scoped installation.

use crate::cli::Cli;
use clap::CommandFactory;
use clap_complete::{generate, Shell};
use colored::Colorize;
use std::env;
use std::fs::{self, File, OpenOptions};
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};
use thiserror::Error;

const BIN_NAME: &str = "keyrex";
const MANAGED_MARKER: &str = "# Generated by KeyRex; managed completion file.";

#[derive(Debug, Error)]
pub enum CompletionError {
    #[error("Could not detect a supported shell; rerun with --shell <shell>")]
    ShellDetectionFailed,

    #[error("Could not determine the user's home directory")]
    HomeDirectoryNotFound,

    #[error("Could not determine the platform configuration directory")]
    ConfigDirectoryNotFound,

    #[error("Could not determine the platform data directory")]
    DataDirectoryNotFound,

    #[error("{variable} must contain an absolute path, got: {path}")]
    RelativeEnvironmentPath {
        variable: &'static str,
        path: PathBuf,
    },

    #[error("Refusing to replace non-regular completion target: {0}")]
    UnsafeTarget(PathBuf),

    #[error(
        "Completion file already exists and is not managed by KeyRex: {0}; rerun with --force to replace it"
    )]
    UnmanagedTarget(PathBuf),

    #[error("Failed to access {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InstallAction {
    Installed,
    Updated,
}

#[derive(Debug, Eq, PartialEq)]
pub struct InstallOutcome {
    pub shell: Shell,
    pub path: PathBuf,
    pub action: InstallAction,
}

/// Generate a completion script and write it to stdout.
pub fn handle_generation(shell: Shell) -> Result<(), CompletionError> {
    let script = generate_completion_script(shell);
    io::stdout()
        .write_all(&script)
        .map_err(|source| CompletionError::Io {
            path: PathBuf::from("<stdout>"),
            source,
        })?;

    eprintln!();
    eprintln!(
        "{}",
        format!(
            "Install automatically with: keyrex completions install --shell {}",
            shell
        )
        .bright_black()
    );
    Ok(())
}

/// Install completions for an explicit shell or the shell detected from the environment.
pub fn handle_install(shell: Option<Shell>, force: bool) -> Result<(), CompletionError> {
    let shell = shell
        .or_else(Shell::from_env)
        .ok_or(CompletionError::ShellDetectionFailed)?;
    let outcome = install_completion(shell, force)?;
    let verb = match outcome.action {
        InstallAction::Installed => "Installed",
        InstallAction::Updated => "Updated",
    };

    eprintln!(
        "{}",
        format!(
            "✓ {} {} completions at {}",
            verb,
            outcome.shell,
            outcome.path.display()
        )
        .green()
        .bold()
    );
    print_refresh_instructions(outcome.shell, &outcome.path);
    Ok(())
}

/// Generate the complete, managed shell script used by stdout generation and installation.
pub fn generate_completion_script(shell: Shell) -> Vec<u8> {
    let mut cmd = Cli::command();
    let mut generated = Vec::new();
    generate(shell, &mut cmd, BIN_NAME, &mut generated);

    let marker = format!("{MANAGED_MARKER}\n");
    if shell == Shell::Zsh && generated.starts_with(b"#compdef ") {
        if let Some(newline) = generated.iter().position(|byte| *byte == b'\n') {
            generated.splice(newline + 1..newline + 1, marker.bytes());
        }
    } else {
        generated.splice(0..0, marker.bytes());
    }

    match shell {
        Shell::Bash => generated.extend_from_slice(BASH_DYNAMIC.as_bytes()),
        Shell::Fish => generated.extend_from_slice(FISH_DYNAMIC.as_bytes()),
        Shell::Zsh => generated.extend_from_slice(ZSH_DYNAMIC.as_bytes()),
        _ => {}
    }
    generated
}

/// Install one managed completion script in the selected shell's user directory.
pub fn install_completion(shell: Shell, force: bool) -> Result<InstallOutcome, CompletionError> {
    let path = resolve_install_path(shell)?;
    install_completion_at(shell, path, force)
}

fn install_completion_at(
    shell: Shell,
    path: PathBuf,
    force: bool,
) -> Result<InstallOutcome, CompletionError> {
    let parent = path
        .parent()
        .ok_or_else(|| CompletionError::UnsafeTarget(path.clone()))?;
    fs::create_dir_all(parent).map_err(|source| io_error(parent, source))?;

    let action = match fs::symlink_metadata(&path) {
        Ok(metadata) => {
            if metadata.file_type().is_symlink() || !metadata.is_file() {
                return Err(CompletionError::UnsafeTarget(path));
            }

            let mut existing = File::open(&path).map_err(|source| io_error(&path, source))?;
            let mut prefix = vec![0; 512];
            let read = existing
                .read(&mut prefix)
                .map_err(|source| io_error(&path, source))?;
            if !prefix[..read]
                .windows(MANAGED_MARKER.len())
                .any(|window| window == MANAGED_MARKER.as_bytes())
                && !force
            {
                return Err(CompletionError::UnmanagedTarget(path));
            }
            InstallAction::Updated
        }
        Err(error) if error.kind() == io::ErrorKind::NotFound => InstallAction::Installed,
        Err(source) => return Err(io_error(&path, source)),
    };

    let script = generate_completion_script(shell);
    replace_file(&path, &script, action == InstallAction::Updated)?;

    Ok(InstallOutcome {
        shell,
        path,
        action,
    })
}

fn replace_file(path: &Path, contents: &[u8], target_exists: bool) -> Result<(), CompletionError> {
    let parent = path
        .parent()
        .ok_or_else(|| CompletionError::UnsafeTarget(path.to_path_buf()))?;
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or(BIN_NAME);
    let mut temporary_path = None;

    for attempt in 0..100_u32 {
        let candidate = parent.join(format!(
            ".{file_name}.{}.{}.tmp",
            std::process::id(),
            attempt
        ));
        match OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&candidate)
        {
            Ok(mut file) => {
                if let Err(source) = file.write_all(contents).and_then(|_| file.sync_all()) {
                    let _ = fs::remove_file(&candidate);
                    return Err(io_error(&candidate, source));
                }
                temporary_path = Some(candidate);
                break;
            }
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(source) => return Err(io_error(&candidate, source)),
        }
    }

    let temporary_path = temporary_path.ok_or_else(|| {
        io_error(
            path,
            io::Error::new(
                io::ErrorKind::AlreadyExists,
                "could not allocate a temporary completion file",
            ),
        )
    })?;

    let result = replace_file_platform(&temporary_path, path, target_exists);
    if result.is_err() {
        let _ = fs::remove_file(&temporary_path);
    }
    result
}

#[cfg(not(windows))]
fn replace_file_platform(
    temporary_path: &Path,
    target_path: &Path,
    _target_exists: bool,
) -> Result<(), CompletionError> {
    fs::rename(temporary_path, target_path).map_err(|source| io_error(target_path, source))
}

#[cfg(windows)]
fn replace_file_platform(
    temporary_path: &Path,
    target_path: &Path,
    target_exists: bool,
) -> Result<(), CompletionError> {
    if !target_exists {
        return fs::rename(temporary_path, target_path)
            .map_err(|source| io_error(target_path, source));
    }

    let backup_path = target_path.with_extension(format!("keyrex-backup-{}", std::process::id()));
    fs::rename(target_path, &backup_path).map_err(|source| io_error(target_path, source))?;
    match fs::rename(temporary_path, target_path) {
        Ok(()) => {
            fs::remove_file(&backup_path).map_err(|source| io_error(&backup_path, source))?;
            Ok(())
        }
        Err(source) => {
            let _ = fs::rename(&backup_path, target_path);
            Err(io_error(target_path, source))
        }
    }
}

fn resolve_install_path(shell: Shell) -> Result<PathBuf, CompletionError> {
    let path = match shell {
        Shell::Bash => bash_completion_home()?.join("completions/keyrex.bash"),
        Shell::Fish => config_home()?.join("fish/completions/keyrex.fish"),
        Shell::Zsh => data_home()?.join("zsh/site-functions/_keyrex"),
        Shell::PowerShell => data_home()?.join("keyrex/completions/_keyrex.ps1"),
        Shell::Elvish => config_home()?.join("elvish/lib/keyrex.elv"),
        _ => return Err(CompletionError::ShellDetectionFailed),
    };
    ensure_absolute("completion directory", path)
}

fn bash_completion_home() -> Result<PathBuf, CompletionError> {
    if let Some(value) = env::var_os("BASH_COMPLETION_USER_DIR").filter(|value| !value.is_empty()) {
        if let Some(path) = env::split_paths(&value).find(|path| !path.as_os_str().is_empty()) {
            return ensure_absolute("BASH_COMPLETION_USER_DIR", path);
        }
    }
    Ok(data_home()?.join("bash-completion"))
}

fn config_home() -> Result<PathBuf, CompletionError> {
    if let Some(path) = environment_path("XDG_CONFIG_HOME")? {
        return Ok(path);
    }
    if cfg!(windows) {
        dirs::config_dir().ok_or(CompletionError::ConfigDirectoryNotFound)
    } else {
        Ok(home_directory()?.join(".config"))
    }
}

fn data_home() -> Result<PathBuf, CompletionError> {
    if let Some(path) = environment_path("XDG_DATA_HOME")? {
        return Ok(path);
    }
    if cfg!(windows) {
        dirs::data_local_dir().ok_or(CompletionError::DataDirectoryNotFound)
    } else {
        Ok(home_directory()?.join(".local/share"))
    }
}

fn environment_path(variable: &'static str) -> Result<Option<PathBuf>, CompletionError> {
    let Some(value) = env::var_os(variable).filter(|value| !value.is_empty()) else {
        return Ok(None);
    };
    ensure_absolute(variable, PathBuf::from(value)).map(Some)
}

fn home_directory() -> Result<PathBuf, CompletionError> {
    dirs::home_dir().ok_or(CompletionError::HomeDirectoryNotFound)
}

fn ensure_absolute(variable: &'static str, path: PathBuf) -> Result<PathBuf, CompletionError> {
    if path.is_absolute() {
        Ok(path)
    } else {
        Err(CompletionError::RelativeEnvironmentPath { variable, path })
    }
}

fn io_error(path: impl AsRef<Path>, source: io::Error) -> CompletionError {
    CompletionError::Io {
        path: path.as_ref().to_path_buf(),
        source,
    }
}

fn print_refresh_instructions(shell: Shell, path: &Path) {
    eprintln!();
    eprintln!("{}", "Refresh the current shell:".cyan().bold());
    match shell {
        Shell::Bash => {
            let quoted = quote_posix(path);
            eprintln!("  {}", format!("source {quoted}").bright_black());
            eprintln!(
                "  If bash-completion is not loaded automatically, add the same line to ~/.bashrc."
            );
        }
        Shell::Fish => {
            eprintln!(
                "  {}",
                format!("source {}", quote_posix(path)).bright_black()
            );
        }
        Shell::Zsh => {
            let directory = path.parent().unwrap_or(path);
            let command = format!(
                "fpath=({} $fpath); autoload -Uz compinit; compinit",
                quote_posix(directory)
            );
            eprintln!("  {}", command.bright_black());
            eprintln!("  Add the same line to ~/.zshrc for future shells.");
        }
        Shell::PowerShell => {
            let command = format!(". {}", quote_powershell(path));
            eprintln!("  {}", command.bright_black());
            eprintln!("  Add the same line to $PROFILE for future shells.");
        }
        Shell::Elvish => {
            eprintln!("  {}", "use keyrex".bright_black());
            eprintln!("  Add the same line to rc.elv for future shells.");
        }
        _ => {}
    }
}

fn quote_posix(path: &Path) -> String {
    format!("'{}'", path.to_string_lossy().replace('\'', "'\\''"))
}

fn quote_powershell(path: &Path) -> String {
    format!("'{}'", path.to_string_lossy().replace('\'', "''"))
}

const BASH_DYNAMIC: &str = r#"

# Dynamic KeyRex key completion for get, update, and remove.
_keyrex_complete_keys_command() {
    local -a keyrex_args=()
    local i=1

    while [[ $i -lt $COMP_CWORD ]]; do
        case "${COMP_WORDS[$i]}" in
            --config)
                if [[ $((i + 1)) -lt $COMP_CWORD ]]; then
                    keyrex_args+=("--config" "${COMP_WORDS[$((i + 1))]}")
                    i=$((i + 2))
                    continue
                fi
                ;;
            --config=*)
                keyrex_args+=("${COMP_WORDS[$i]}")
                ;;
        esac
        i=$((i + 1))
    done

    command keyrex "${keyrex_args[@]}" keys 2>/dev/null
}

_keyrex_complete_with_keys() {
    local cur subcommand
    local subcommand_index=0
    local i=1
    cur="${COMP_WORDS[COMP_CWORD]}"

    while [[ $i -lt $COMP_CWORD ]]; do
        case "${COMP_WORDS[$i]}" in
            --config)
                i=$((i + 2))
                continue
                ;;
            --config=*)
                i=$((i + 1))
                continue
                ;;
            -*)
                i=$((i + 1))
                continue
                ;;
            *)
                subcommand="${COMP_WORDS[$i]}"
                subcommand_index=$i
                break
                ;;
        esac
    done

    case "$subcommand" in
        get|update|remove)
            if [[ $COMP_CWORD -eq $((subcommand_index + 1)) ]]; then
                COMPREPLY=()
                while IFS= read -r key; do
                    [[ "$key" == "$cur"* ]] && COMPREPLY+=("$key")
                done < <(_keyrex_complete_keys_command)
                return 0
            fi
            ;;
    esac

    _keyrex "$@"
}

complete -F _keyrex_complete_with_keys -o bashdefault -o default keyrex
"#;

const FISH_DYNAMIC: &str = r#"

# Dynamic KeyRex key completion for get, update, and remove.
function __keyrex_complete_keys
    set -l tokens (commandline -opc)
    set -l keyrex_args
    set -l i 1

    while test $i -le (count $tokens)
        switch $tokens[$i]
            case --config
                set -l next (math $i + 1)
                if test $next -le (count $tokens)
                    set -a keyrex_args --config $tokens[$next]
                    set i (math $i + 2)
                    continue
                end
            case '--config=*'
                set -a keyrex_args $tokens[$i]
        end
        set i (math $i + 1)
    end

    command keyrex $keyrex_args keys 2>/dev/null
end

complete -c keyrex -n '__fish_seen_subcommand_from get update remove' -f -a '(__keyrex_complete_keys)'
"#;

const ZSH_DYNAMIC: &str = r#"

# Dynamic KeyRex key completion for get, update, and remove.
_keyrex_complete_keys_command() {
    local -a keyrex_args keys
    local -i i=2

    while (( i < CURRENT )); do
        case "${words[$i]}" in
            --config)
                if (( i + 1 < CURRENT )); then
                    keyrex_args+=(--config "${words[$((i + 1))]}")
                    (( i += 2 ))
                    continue
                fi
                ;;
            --config=*)
                keyrex_args+=("${words[$i]}")
                ;;
        esac
        (( i++ ))
    done

    keys=("${(@f)$(command keyrex "${keyrex_args[@]}" keys 2>/dev/null)}")
    compadd -a keys
}

_keyrex_complete_with_keys() {
    local subcommand
    local -i subcommand_index=0
    local -i i=2

    while (( i < CURRENT )); do
        case "${words[$i]}" in
            --config)
                (( i += 2 ))
                continue
                ;;
            --config=*)
                (( i++ ))
                continue
                ;;
            -*)
                (( i++ ))
                continue
                ;;
            *)
                subcommand="${words[$i]}"
                subcommand_index=$i
                break
                ;;
        esac
    done

    case "$subcommand" in
        get|update|remove)
            if (( CURRENT == subcommand_index + 1 )); then
                _keyrex_complete_keys_command
                return
            fi
            ;;
    esac

    _keyrex "$@"
}

compdef _keyrex_complete_with_keys keyrex
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn test_path(name: &str) -> PathBuf {
        std::env::temp_dir()
            .join("keyrex_completion_tests")
            .join(format!("{name}-{}", std::process::id()))
    }

    #[test]
    fn test_generated_scripts_are_marked() {
        for shell in [
            Shell::Bash,
            Shell::Elvish,
            Shell::Fish,
            Shell::PowerShell,
            Shell::Zsh,
        ] {
            let script = String::from_utf8(generate_completion_script(shell)).unwrap();
            assert!(script.contains(MANAGED_MARKER));
        }
    }

    #[test]
    fn test_dynamic_keys_are_limited_to_supported_shells() {
        for shell in [Shell::Bash, Shell::Fish, Shell::Zsh] {
            let script = String::from_utf8(generate_completion_script(shell)).unwrap();
            assert!(script.contains("Dynamic KeyRex key completion"));
        }
        for shell in [Shell::PowerShell, Shell::Elvish] {
            let script = String::from_utf8(generate_completion_script(shell)).unwrap();
            assert!(!script.contains("Dynamic KeyRex key completion"));
        }
    }

    #[test]
    fn test_zsh_compdef_header_remains_first() {
        let script = String::from_utf8(generate_completion_script(Shell::Zsh)).unwrap();
        assert!(script.starts_with("#compdef keyrex\n"));
        assert!(script.lines().take(3).any(|line| line == MANAGED_MARKER));
    }

    #[test]
    fn test_install_creates_parent_directories() {
        let root = test_path("create");
        let target = root.join("nested/completions/keyrex.bash");
        let _ = fs::remove_dir_all(&root);

        let outcome = install_completion_at(Shell::Bash, target.clone(), false).unwrap();
        assert_eq!(outcome.action, InstallAction::Installed);
        assert!(target.is_file());
        assert!(fs::read_to_string(&target)
            .unwrap()
            .contains(MANAGED_MARKER));

        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn test_managed_install_updates_without_force() {
        let root = test_path("managed-update");
        let target = root.join("keyrex.fish");
        let _ = fs::remove_dir_all(&root);

        let first = install_completion_at(Shell::Fish, target.clone(), false).unwrap();
        let second = install_completion_at(Shell::Fish, target.clone(), false).unwrap();
        assert_eq!(first.action, InstallAction::Installed);
        assert_eq!(second.action, InstallAction::Updated);

        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn test_unmanaged_install_requires_force() {
        let root = test_path("unmanaged");
        let target = root.join("_keyrex");
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&root).unwrap();
        fs::write(&target, "# custom completion\n").unwrap();

        assert!(matches!(
            install_completion_at(Shell::Zsh, target.clone(), false),
            Err(CompletionError::UnmanagedTarget(_))
        ));
        let outcome = install_completion_at(Shell::Zsh, target.clone(), true).unwrap();
        assert_eq!(outcome.action, InstallAction::Updated);
        assert!(fs::read_to_string(&target)
            .unwrap()
            .contains(MANAGED_MARKER));

        fs::remove_dir_all(root).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn test_install_refuses_symlink_target_even_with_force() {
        use std::os::unix::fs::symlink;

        let root = test_path("symlink");
        let target = root.join("keyrex.bash");
        let destination = root.join("custom.bash");
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&root).unwrap();
        fs::write(&destination, "custom\n").unwrap();
        symlink(&destination, &target).unwrap();

        assert!(matches!(
            install_completion_at(Shell::Bash, target, true),
            Err(CompletionError::UnsafeTarget(_))
        ));
        assert_eq!(fs::read_to_string(&destination).unwrap(), "custom\n");

        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn test_shell_quoting_handles_single_quotes() {
        assert_eq!(quote_posix(Path::new("/tmp/a'b")), "'/tmp/a'\\''b'");
        assert_eq!(quote_powershell(Path::new("/tmp/a'b")), "'/tmp/a''b'");
    }

    #[test]
    fn test_relative_install_roots_are_rejected() {
        assert!(matches!(
            ensure_absolute("XDG_CONFIG_HOME", PathBuf::from("relative/path")),
            Err(CompletionError::RelativeEnvironmentPath { .. })
        ));
    }
}
